# Generated by Django 5.1.7 on 2025-04-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_paket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
