# Generated by Django 5.1.7 on 2025-04-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_server_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
