# Generated by Django 4.2.7 on 2025-06-01 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_server_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('ip_range', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='paket',
            name='ip_pool',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='paket_list', to='app.ippool'),
            preserve_default=False,
        ),
    ]
