# Generated by Django 4.2.7 on 2025-06-01 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_nama_ippool_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('pppoe', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=True)),
                ('id_paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paket_list', to='app.paket')),
                ('id_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_list', to='app.server')),
            ],
        ),
    ]
