# Generated by Django 4.2.7 on 2025-06-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_client_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
