# Generated by Django 4.2.7 on 2025-06-04 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_client_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='ippool',
            name='id_server',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='server', to='app.server'),
            preserve_default=False,
        ),
    ]
