# Generated by Django 4.2.7 on 2025-06-04 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_ippool_id_server'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paket',
            old_name='ip_pool',
            new_name='id_ip_pool',
        ),
    ]
