# Generated by Django 4.2.7 on 2025-06-11 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_client_temp_address_client_temp_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='temp_paket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_paket', to='app.paket'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_paket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pakets', to='app.paket'),
        ),
        migrations.AlterField(
            model_name='ippool',
            name='id_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='app.server'),
        ),
        migrations.AlterField(
            model_name='paket',
            name='id_ip_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_pools', to='app.ippool'),
        ),
    ]
