# Generated by Django 4.2.7 on 2025-06-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_client_temp_paket_alter_client_id_paket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='isApproved',
            field=models.BooleanField(default=True),
        ),
    ]
