# Generated by Django 4.2.7 on 2025-08-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_client_email_client_isservernull_client_temp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='isPayed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
