# Generated by Django 4.2.7 on 2025-08-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_client_ispayed_alter_client_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lastPayment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
