# Generated by Django 4.2.7 on 2025-08-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_client_lastpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redaman',
            old_name='id_client',
            new_name='pppoe',
        ),
        migrations.AlterField(
            model_name='redaman',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
