# Generated by Django 4.2.7 on 2025-08-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_id_client_redaman_pppoe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='genieacs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
