# Generated by Django 4.2.7 on 2025-08-31 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_server_genieacs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redaman',
            old_name='pppoe',
            new_name='id_client',
        ),
    ]
