# Generated by Django 4.2.7 on 2025-08-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_rename_pppoe_redaman_id_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redaman',
            name='create_at',
            field=models.DateTimeField(),
        ),
    ]
