# Generated by Django 4.2.7 on 2025-08-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_redaman_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redaman',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
