# Generated by Django 4.2.7 on 2025-09-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_gateway_server_lat_server_long_client_gateway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='parent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
