# Generated by Django 4.2.7 on 2025-09-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_gateway_parent_alter_gateway_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='isFromServer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='parent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
