# Generated by Django 4.2.7 on 2025-09-04 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_gateway_isfromserver_alter_gateway_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='isFromServer',
        ),
    ]
