# Generated by Django 4.2.7 on 2025-09-04 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_gateway_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateways', to='app.server'),
        ),
    ]
