# Generated by Django 4.2.7 on 2025-09-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_gateway_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='parent',
        ),
        migrations.AddField(
            model_name='gateway',
            name='parent_lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='parent_long',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
