# Generated by Django 4.2.7 on 2025-09-04 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_gateway_parent_gateway_parent_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='id_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateways', to='app.server'),
        ),
    ]
