# Generated by Django 4.2.7 on 2025-09-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_gateway_id_server'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gateway',
            old_name='id_server',
            new_name='server',
        ),
    ]
