# Generated by Django 4.2.7 on 2025-09-11 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_rename_id_server_gateway_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='lastPayment',
        ),
        migrations.AlterField(
            model_name='gateway',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to='app.server'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastPayment', models.DateField(blank=True, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('id_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_transaction', to='app.client')),
            ],
        ),
    ]
