# Generated by Django 4.2.7 on 2025-09-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_server_genieacs'),
    ]

    operations = [
        migrations.AddField(
            model_name='ippool',
            name='total_ips',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paket',
            name='total_ips',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paket',
            name='used_ips',
            field=models.IntegerField(default=0),
        ),
    ]
