# Generated by Django 4.2.7 on 2025-09-12 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_ippool_total_ips_paket_total_ips_paket_used_ips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paket',
            name='total_ips',
        ),
    ]
