# Generated by Django 4.2.7 on 2025-09-13 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_remove_paket_total_ips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='lastPayment',
        ),
    ]
