# Generated by Django 4.2.7 on 2025-09-13 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_remove_transaction_lastpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='activated_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
