# Generated by Django 4.2.7 on 2025-09-15 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_client_activated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('can_change_is_active', 'Can change isActive field only'), ('can_change_is_payed', 'Can change isPayed field only')]},
        ),
    ]
