# Generated by Django 4.2.7 on 2025-09-15 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_client_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('can_change_is_active', 'Can change active or nonactive client'), ('can_change_is_payed', 'Can change payment status + write transaction')]},
        ),
        migrations.AlterModelOptions(
            name='paket',
            options={'permissions': [('can_change_price', 'Can change Price only')]},
        ),
    ]
