# Generated by Django 4.2.7 on 2025-09-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_client_options_alter_paket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('can_change_is_active', 'Can change active or nonactive client'), ('can_change_is_payed', 'Can change payment status + write transaction'), ('can_verif_edited', 'Can verif edited client')]},
        ),
    ]
