# Generated by Django 4.2.7 on 2025-09-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_client_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='lat',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='long',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='parent_lat',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='parent_long',
            field=models.CharField(max_length=255),
        ),
    ]
