# Generated by Django 4.2.7 on 2025-10-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_alter_gateway_lat_alter_gateway_long_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut_network_after', models.IntegerField(default=2, help_text='Berapa hari setelah jatuh tempo layanan diputus')),
                ('reminder_before_bill', models.IntegerField(default=3, help_text='Berapa hari sebelum cut date reminder dikirim')),
                ('interval_check', models.IntegerField(default=300, help_text='Interval pengecekan (detik)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
