# Generated by Django 4.2.7 on 2025-10-24 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_configsystem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigSystem',
        ),
    ]
