# Generated by Django 4.2.7 on 2025-10-24 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_delete_configsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='app.server'),
        ),
        migrations.AddField(
            model_name='paket',
            name='id_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pakets', to='app.server'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_paket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='app.paket'),
        ),
        migrations.AlterField(
            model_name='client',
            name='temp_paket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_clients', to='app.paket'),
        ),
        migrations.AlterField(
            model_name='ippool',
            name='id_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pools', to='app.server'),
        ),
        migrations.AlterField(
            model_name='paket',
            name='id_ip_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pakets', to='app.ippool'),
        ),
        migrations.AlterField(
            model_name='redaman',
            name='id_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redamans', to='app.client'),
        ),
    ]
