# Generated by Django 4.2.7 on 2025-10-24 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_client_id_server_paket_id_server_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redaman',
            name='id_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redamans', to='app.client'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_transaction', to='app.client'),
        ),
    ]
