# Generated by Django 5.1.7 on 2025-04-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_paket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paket',
            name='price',
            field=models.IntegerField(),
        ),
    ]
