# Generated by Django 4.2.7 on 2025-06-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_ippool_paket_ip_pool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ippool',
            old_name='nama',
            new_name='name',
        ),
    ]
