# Generated by Django 4.2.7 on 2025-06-04 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_rename_ip_pool_paket_id_ip_pool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id_server',
        ),
    ]
