# Generated by Django 4.2.7 on 2025-06-05 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_remove_client_id_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_paket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pakets', to='polls.paket'),
        ),
        migrations.AlterField(
            model_name='ippool',
            name='id_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='polls.server'),
        ),
        migrations.AlterField(
            model_name='paket',
            name='id_ip_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_pools', to='polls.ippool'),
        ),
    ]
