# Generated by Django 4.2.7 on 2025-06-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_client_id_paket_alter_ippool_id_server_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
