# Generated by Django 4.2.7 on 2025-08-20 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_client_local_ip_client_temp_local_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_paket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pakets', to='polls.paket'),
        ),
        migrations.AlterField(
            model_name='client',
            name='temp_paket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_paket', to='polls.paket'),
        ),
        migrations.AlterField(
            model_name='ippool',
            name='id_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='polls.server'),
        ),
        migrations.AlterField(
            model_name='paket',
            name='id_ip_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_pools', to='polls.ippool'),
        ),
        migrations.AlterField(
            model_name='redaman',
            name='id_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='polls.client'),
        ),
    ]
