# Generated by Django 4.2.7 on 2025-08-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_alter_client_id_paket_alter_client_temp_paket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='isServerNull',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='temp_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
